services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
