services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=testuser
      - FTP_PASS=testpass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - FILE_OPEN_MODE=0666
      - LOCAL_UMASK=022
      - LOG_STDOUT=1
    volumes:
      - ./ftpdata:/home/vsftpd
